language: python # Can use any language here, but if it's not 'python'
                 # it becomes necessary to pass '--user' to pip when installing hererocks.
sudo: false      # Use container-based infrastructure.

env:
  - LUA="lua 5.1"

before_install:
  - pip install hererocks
  - hererocks env --$LUA -rlatest    # Use latest LuaRocks, install into 'env' directory.
  - source env/bin/activate          # Add directory with all installed binaries to PATH.
  - luarocks install luacheck

#install:
#  - luarocks make # Install the rock, assuming there is a rockspec
#                  # in the root of the repository.

script:
  # '--enable 1' means 'global = true'
  # IDEs tend to have issues with 'global = true', as they work on a per-file basis
  # this allows us to use the same .luacheckrc for both travis and IDEs
  # (Disabled for now)
  - luacheck luaui luarules --enable 1
  - ./autotest.sh
